Vagrant.configure("2") do |config|
  config.vm.box = "generic/alpine312"
  config.vm.define "misaac-cS" do |server|
    server.vm.hostname = "misaac-cS"
    server.vm.network "private_network", ip: "192.168.56.110"
    server.vm.provider "virtualbox" do |vbs|
      vbs.memory = 1024
      vbs.name = "misaac-cS"
      vbs.cpus = 1
    end
    server.vm.provision "file", source: "postgres.yaml", destination: "~/postgres.yaml"
    server.vm.provision "file", source: "srcs", destination: "~/srcs"
    server.vm.provision "shell", inline: <<-SHELL
      curl -sfL https://get.k3s.io | INSTALL_K3S_EXEC="--node-ip=192.168.56.110 --write-kubeconfig-mode 644" sh - 
      until kubectl get all ; do  
        echo "waiting for kubernetes"
        sleep 1
      done
      kubectl create configmap app-one-html --from-file=/home/vagrant/srcs/app1/index.html
      kubectl create configmap app-two-html --from-file=/home/vagrant/srcs/app2/index.html
      kubectl create configmap app-three-html --from-file=/home/vagrant/srcs/app3/index.html
      kubectl apply -f /home/vagrant/postgres.yaml
    SHELL
  end
end
